version: '3.8'
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL="https://api.josh.tech.mooo.com/docs"
    ports:
      - "3000:80"

  backend:
    image: backend:latest
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      - BACKEND_CORS_ORIGINS="http://localhost,http://localhost:5173,https://localhost,https://localhost:5173"
      - SECRET_KEY=hangethis123
      - PROJECT_NAME=Full Stack FastAPI Project
      - FIRST_SUPERUSER=devops@hng.tech
      - FIRST_SUPERUSER_PASSWORD=devops#HNG11
      - USERS_OPEN_REGISTRATION=true
      - POSTGRES_SERVER=aws-0-eu-central-1.pooler.supabase.com
      - POSTGRES_PORT=6543
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres.edlycoygajaszpwqasyg
      - POSTGRES_PASSWORD=Badoo070123$

  postgres:
    image: 'postgres:15'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db


  
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81' # Admin UI
    volumes:
      - ./data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
      - adminer

